# Generated by Django 5.0.1 on 2024-01-28 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2024, 1, 28, 21, 37, 51, 169716)),
        ),
    ]
